[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config.rust-analyzer]
cargo.loadOutDirsFromCheck = true
procMacro.enable = true

[languages.rust]
language-server = "rust-analyzer"
